config/routes.rb
Rails.application.routes.draw do
  resources :aadresses
  resources :cats
  root "products#index"
  resources :addresses

  resources :homes
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  resources :products do
    resources :likes
  	get "/add_to_cart", to: "products#add_to_cart"
    get "/add_to_wishlist", to: "products#add_to_wishlist"
    get "/remove_to_wishlist", to: "products#remove_to_wishlist"


  get "/like_products", to: "products#add_to_like"
  get "/dislike_products", to: "products#remove_to_like"
  end
  resources :cart_items do
  	get "/remove", to: "cart_items#destroy"
  end
  resources :wishlists do
    get "/remove_to_wishlist", to: "products#remove_to_wishlist"

  end 
  get "/search", to: "products#search"

  match '/auth/:provider/callback', :to => 'sessions#create', via: [:get, :post]
  match '/auth/failure', :to => 'sessions#failure', via: [:get, :post]


  resources :sub_categories
  resources :categories
  resources :contacts

  
  post "/create-checkout-session", to: "cart_items#checkout"
  post "/checkout_razor", to: "cart_items#checkout_razor"

  get "/carts/success", to: "cart_items#success"
  get "/carts/cancel", to: "cart_items#cancel"
  get "/success", to: "cart_items#success_page"
  

  post "/cash_on_dilevery", to: "cart_items#cash_on_dilevery"

  get "/cart_items_razor_success", to: "cart_items#cart_items_razor_success"

  get "/destroy/:product_id", to: "cart_items#destroy"

  get "/orders", to: "orders#index"
  get "/cancel/:order_id", to: "orders#cancel"


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/aadress.rb
class Aadress < ApplicationRecord
	belongs_to :user
end

app/models/address.rb
class Address < ApplicationRecord
	belongs_to :user
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/booking.rb
class Booking < ApplicationRecord
end

app/models/cart.rb
class Cart < ApplicationRecord
	acts_as_shopping_cart_using :cart_item
	belongs_to :user
	def self.random
		"TSsd" + Random.rand(10000).to_s
	end
	
end

app/models/cart_item.rb
class CartItem < ActiveRecord::Base
  acts_as_shopping_cart_item_for :cart
end

app/models/cat.rb
class Cat < ApplicationRecord
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :sub_categories
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :product
  belongs_to :user
end

app/models/order_booking.rb
class OrderBooking < ApplicationRecord
	belongs_to :user
end

app/models/order_status.rb
class OrderStatus < ApplicationRecord
	enum status: %i[created inprocess dilevered cancelled]
	enum refund: %i[in-process success failed]
end

app/models/product.rb
class Product < ApplicationRecord
	belongs_to :sub_category
	has_many :likes, dependent: :destroy
	delegate :category, to: :sub_category
	mount_uploader :image, ImageUploader

end

app/models/sub_category.rb
class SubCategory < ApplicationRecord
	belongs_to :category
	has_many :products
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one :cart
  has_many :wishlists
  has_many :likes, dependent: :destroy

  has_many :authentications, dependent: :destroy
	validates :email, :uniqueness => {:allow_blank => true}

	has_many :addresses
	has_many :order_bookings

end

app/models/wishlist.rb
class Wishlist < ApplicationRecord
	belongs_to :user
	belongs_to :product
end

app/controllers/aadresses_controller.rb
class AadressesController < InheritedResources::Base

  private

    def aadress_params
      params.require(:aadress).permit(:email, :name, :phone, :line1, :country, :state, :pincode, :user_id)
    end

end

app/helpers/aadresses_helper.rb
module AadressesHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/aadresses/_form.html.erb
<%= form_with(model: aadress, local: true) do |form| %>
  <% if aadress.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(aadress.errors.count, "error") %> prohibited this aadress from being saved:</h2>

      <ul>
        <% aadress.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>

  <div class="field">
    <%= form.label :line1 %>
    <%= form.text_field :line1 %>
  </div>

  <div class="field">
    <%= form.label :country %>
    <%= form.text_field :country %>
  </div>

  <div class="field">
    <%= form.label :state %>
    <%= form.text_field :state %>
  </div>

  <div class="field">
    <%= form.label :pincode %>
    <%= form.number_field :pincode %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/aadresses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Aadresses</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Name</th>
      <th>Phone</th>
      <th>Line1</th>
      <th>Country</th>
      <th>State</th>
      <th>Pincode</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @aadresses.each do |aadress| %>
      <tr>
        <td><%= aadress.email %></td>
        <td><%= aadress.name %></td>
        <td><%= aadress.phone %></td>
        <td><%= aadress.line1 %></td>
        <td><%= aadress.country %></td>
        <td><%= aadress.state %></td>
        <td><%= aadress.pincode %></td>
        <td><%= aadress.user_id %></td>
        <td><%= link_to 'Show', aadress %></td>
        <td><%= link_to 'Edit', edit_aadress_path(aadress) %></td>
        <td><%= link_to 'Destroy', aadress, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Aadress', new_aadress_path %>

app/views/aadresses/new.html.erb
<h1>New Aadress</h1>

<%= render 'form', aadress: @aadress %>

<%= link_to 'Back', aadresses_path %>

app/views/aadresses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @aadress.email %>
</p>

<p>
  <strong>Name:</strong>
  <%= @aadress.name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @aadress.phone %>
</p>

<p>
  <strong>Line1:</strong>
  <%= @aadress.line1 %>
</p>

<p>
  <strong>Country:</strong>
  <%= @aadress.country %>
</p>

<p>
  <strong>State:</strong>
  <%= @aadress.state %>
</p>

<p>
  <strong>Pincode:</strong>
  <%= @aadress.pincode %>
</p>

<p>
  <strong>User:</strong>
  <%= @aadress.user_id %>
</p>

<%= link_to 'Edit', edit_aadress_path(@aadress) %> |
<%= link_to 'Back', aadresses_path %>