config/routes.rb
Rails.application.routes.draw do
  resources :aadresses
  resources :cats
  root "products#index"
  resources :addresses

  resources :homes
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  resources :products do
    resources :likes
  	get "/add_to_cart", to: "products#add_to_cart"
    get "/add_to_wishlist", to: "products#add_to_wishlist"
    get "/remove_to_wishlist", to: "products#remove_to_wishlist"


  get "/like_products", to: "products#add_to_like"
  get "/dislike_products", to: "products#remove_to_like"
  end
  resources :cart_items do
  	get "/remove", to: "cart_items#destroy"
  end
  resources :wishlists do
    get "/remove_to_wishlist", to: "products#remove_to_wishlist"

  end 
  get "/search", to: "products#search"

  match '/auth/:provider/callback', :to => 'sessions#create', via: [:get, :post]
  match '/auth/failure', :to => 'sessions#failure', via: [:get, :post]


  resources :sub_categories
  resources :categories
  resources :contacts

  
  post "/create-checkout-session", to: "cart_items#checkout"
  post "/checkout_razor", to: "cart_items#checkout_razor"

  get "/carts/success", to: "cart_items#success"
  get "/carts/cancel", to: "cart_items#cancel"
  get "/success", to: "cart_items#success_page"
  

  post "/cash_on_dilevery", to: "cart_items#cash_on_dilevery"

  get "/cart_items_razor_success", to: "cart_items#cart_items_razor_success"

  get "/destroy/:product_id", to: "cart_items#destroy"

  get "/orders", to: "orders#index"
  get "/cancel/:order_id", to: "orders#cancel"


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/aadress.rb
class Aadress < ApplicationRecord
	belongs_to :user
end

app/models/address.rb
class Address < ApplicationRecord
	belongs_to :user
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/authentication.rb
class Authentication < ApplicationRecord
	belongs_to :user
 def self.from_omniauth(auth)
    authenticate = where(provider: auth['provider'], :uid=>auth['uid']).first_or_initialize
    register_user = User.find_by(email: auth.info.email)
    if authenticate.user
      return authenticate.user
    elsif register_user
      register_user.authentications.create(provider: auth['provider'], :uid=>auth['uid'])
      return register_user
    else
      user = User.new(
        email: auth.info.try(:email),                      
        password: Devise.friendly_token.first(8)
      )
      if user.email.blank?
        user.email=auth.extra.raw_info.id.to_s+"@gmail.com"
      end
      user.save!(:validate => false)
      user.authentications.create(provider: auth['provider'], :uid=>auth['uid'],token: auth["credentials"]["token"])
      return user
   end
  end
end

app/models/booking.rb
class Booking < ApplicationRecord
end

app/models/cart.rb
class Cart < ApplicationRecord
	acts_as_shopping_cart_using :cart_item
	belongs_to :user
	def self.random
		"TSsd" + Random.rand(10000).to_s
	end
	
end

app/models/cart_item.rb
class CartItem < ActiveRecord::Base
  acts_as_shopping_cart_item_for :cart
end

app/models/cat.rb
class Cat < ApplicationRecord
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :sub_categories
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :product
  belongs_to :user
end

app/models/order_booking.rb
class OrderBooking < ApplicationRecord
	belongs_to :user
end

app/models/order_status.rb
class OrderStatus < ApplicationRecord
	enum status: %i[created inprocess dilevered cancelled]
	enum refund: %i[in-process success failed]
end

app/models/product.rb
class Product < ApplicationRecord
	belongs_to :sub_category
	has_many :likes, dependent: :destroy
	delegate :category, to: :sub_category
	mount_uploader :image, ImageUploader

end

app/models/sub_category.rb
class SubCategory < ApplicationRecord
	belongs_to :category
	has_many :products
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one :cart
  has_many :wishlists
  has_many :likes, dependent: :destroy

  has_many :authentications, dependent: :destroy
	validates :email, :uniqueness => {:allow_blank => true}

	has_many :addresses
	has_many :order_bookings

end

app/models/wishlist.rb
class Wishlist < ApplicationRecord
	belongs_to :user
	belongs_to :product
end

app/controllers/sub_categories_controller.rb
class SubCategoriesController < ApplicationController
  before_action :set_sub_category, only: %i[ show edit update destroy ]

  # GET /sub_categories or /sub_categories.json
  def index
    @sub_categories = SubCategory.all
  end

  # GET /sub_categories/1 or /sub_categories/1.json
  def show
  end

  # GET /sub_categories/new
  def new
    @sub_category = SubCategory.new
  end

  # GET /sub_categories/1/edit
  def edit
  end

  # POST /sub_categories or /sub_categories.json
  def create
    @sub_category = SubCategory.new(sub_category_params)

    respond_to do |format|
      if @sub_category.save
        format.html { redirect_to sub_category_url(@sub_category), notice: "Sub category was successfully created." }
        format.json { render :show, status: :created, location: @sub_category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @sub_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sub_categories/1 or /sub_categories/1.json
  def update
    respond_to do |format|
      if @sub_category.update(sub_category_params)
        format.html { redirect_to sub_category_url(@sub_category), notice: "Sub category was successfully updated." }
        format.json { render :show, status: :ok, location: @sub_category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @sub_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sub_categories/1 or /sub_categories/1.json
  def destroy
    @sub_category.destroy

    respond_to do |format|
      format.html { redirect_to sub_categories_url, notice: "Sub category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sub_category
      @sub_category = SubCategory.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def sub_category_params
      params.require(:sub_category).permit(:category_id, :title)
    end
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/sub_categories_helper.rb
module SubCategoriesHelper
end

app/views/sub_categories/_form.html.erb
<%= form_with(model: sub_category, local: true) do |form| %>
  <% if sub_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sub_category.errors.count, "error") %> prohibited this sub_category from being saved:</h2>

      <ul>
        <% sub_category.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :category_id %>
    <%= form.number_field :category_id %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/sub_categories/edit.html.erb
<h1>Editing Sub Category</h1>

<%= render 'form', sub_category: @sub_category %>

<%= link_to 'Show', @sub_category %> |
<%= link_to 'Back', sub_categories_path %>

app/views/sub_categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sub Categories</h1>

<table>
  <thead>
    <tr>
      <th>Category</th>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sub_categories.each do |sub_category| %>
      <tr>
        <td><%= sub_category.category_id %></td>
        <td><%= sub_category.title %></td>
        <td><%= link_to 'Show', sub_category %></td>
        <td><%= link_to 'Edit', edit_sub_category_path(sub_category) %></td>
        <td><%= link_to 'Destroy', sub_category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sub Category', new_sub_category_path %>

app/views/sub_categories/new.html.erb
<h1>New Sub Category</h1>

<%= render 'form', sub_category: @sub_category %>

<%= link_to 'Back', sub_categories_path %>

app/views/sub_categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Category:</strong>
  <%= @sub_category.category_id %>
</p>

<p>
  <strong>Title:</strong>
  <%= @sub_category.title %>
</p>

<%= link_to 'Edit', edit_sub_category_path(@sub_category) %> |
<%= link_to 'Back', sub_categories_path %>