config/routes.rb
Rails.application.routes.draw do
  resources :aadresses
  resources :cats
  root "products#index"
  resources :addresses

  resources :homes
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  resources :products do
    resources :likes
  	get "/add_to_cart", to: "products#add_to_cart"
    get "/add_to_wishlist", to: "products#add_to_wishlist"
    get "/remove_to_wishlist", to: "products#remove_to_wishlist"


  get "/like_products", to: "products#add_to_like"
  get "/dislike_products", to: "products#remove_to_like"
  end
  resources :cart_items do
  	get "/remove", to: "cart_items#destroy"
  end
  resources :wishlists do
    get "/remove_to_wishlist", to: "products#remove_to_wishlist"

  end 
  get "/search", to: "products#search"

  match '/auth/:provider/callback', :to => 'sessions#create', via: [:get, :post]
  match '/auth/failure', :to => 'sessions#failure', via: [:get, :post]


  resources :sub_categories
  resources :categories
  resources :contacts

  
  post "/create-checkout-session", to: "cart_items#checkout"
  post "/checkout_razor", to: "cart_items#checkout_razor"

  get "/carts/success", to: "cart_items#success"
  get "/carts/cancel", to: "cart_items#cancel"
  get "/success", to: "cart_items#success_page"
  

  post "/cash_on_dilevery", to: "cart_items#cash_on_dilevery"

  get "/cart_items_razor_success", to: "cart_items#cart_items_razor_success"

  get "/destroy/:product_id", to: "cart_items#destroy"

  get "/orders", to: "orders#index"
  get "/cancel/:order_id", to: "orders#cancel"


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/aadress.rb
class Aadress < ApplicationRecord
	belongs_to :user
end

app/models/address.rb
class Address < ApplicationRecord
	belongs_to :user
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/authentication.rb
class Authentication < ApplicationRecord
	belongs_to :user
 def self.from_omniauth(auth)
    authenticate = where(provider: auth['provider'], :uid=>auth['uid']).first_or_initialize
    register_user = User.find_by(email: auth.info.email)
    if authenticate.user
      return authenticate.user
    elsif register_user
      register_user.authentications.create(provider: auth['provider'], :uid=>auth['uid'])
      return register_user
    else
      user = User.new(
        email: auth.info.try(:email),                      
        password: Devise.friendly_token.first(8)
      )
      if user.email.blank?
        user.email=auth.extra.raw_info.id.to_s+"@gmail.com"
      end
      user.save!(:validate => false)
      user.authentications.create(provider: auth['provider'], :uid=>auth['uid'],token: auth["credentials"]["token"])
      return user
   end
  end
end

app/models/booking.rb
class Booking < ApplicationRecord
end

app/models/cart.rb
class Cart < ApplicationRecord
	acts_as_shopping_cart_using :cart_item
	belongs_to :user
	def self.random
		"TSsd" + Random.rand(10000).to_s
	end
	
end

app/models/cart_item.rb
class CartItem < ActiveRecord::Base
  acts_as_shopping_cart_item_for :cart
end

app/models/cat.rb
class Cat < ApplicationRecord
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :sub_categories
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :product
  belongs_to :user
end

app/models/order_booking.rb
class OrderBooking < ApplicationRecord
	belongs_to :user
end

app/models/order_status.rb
class OrderStatus < ApplicationRecord
	enum status: %i[created inprocess dilevered cancelled]
	enum refund: %i[in-process success failed]
end

app/models/product.rb
class Product < ApplicationRecord
	belongs_to :sub_category
	has_many :likes, dependent: :destroy
	delegate :category, to: :sub_category
	mount_uploader :image, ImageUploader

end

app/models/sub_category.rb
class SubCategory < ApplicationRecord
	belongs_to :category
	has_many :products
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one :cart
  has_many :wishlists
  has_many :likes, dependent: :destroy

  has_many :authentications, dependent: :destroy
	validates :email, :uniqueness => {:allow_blank => true}

	has_many :addresses
	has_many :order_bookings

end

app/models/wishlist.rb
class Wishlist < ApplicationRecord
	belongs_to :user
	belongs_to :product
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]

  # GET /products or /products.json
  def index
    @products = Product.all
  end

  def search
    @products = Product.where(["LOWER(title) LIKE ?","%#{params[:search].downcase}%"])
  end

  # GET /products/1 or /products/1.json
  def show

  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit

  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to product_url(@product), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def add_to_cart
    @product = Product.find_by(id: params[:product_id])
    if current_user.cart.present?
      @cart = current_user.cart
    else
      @cart = Cart.create(user_id: current_user.id)
    end

    @cart.add(@product, @product.price)
    redirect_to cart_items_path
  end

  def add_to_wishlist
    @product = Product.find_by(id: params[:product_id])
    Wishlist.create(user_id: current_user.id, product_id: params[:product_id])
    redirect_to wishlists_path
  end

  def remove_to_wishlist
    Wishlist.find(params[:wishlist_id]).destroy
    redirect_to wishlists_path    
  end
  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_url(@product), notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def add_to_like
    @product = Product.find_by(id: params[:product_id])
    Like.create(user_id: current_user.id, product_id: params[:product_id])
    # redirect_to request.referrer
    redirect_back fallback_location: root_path
  end

  def remove_to_like
    Like.where(user_id: current_user.id, product_id: params[:product_id]).destroy_all
    redirect_back fallback_location: root_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:title, :description, :price, :image, :size, :sub_category_id)
    end

end

app/helpers/cats_helper.rb
module CatsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div class="field">
    <%= form.label :size %>
    <%= form.text_area :size %>
  </div>

  <div class="field">
    <%= form.label :sub_category %>
    <%#= form.file_field :sub_category %>
    <%= form.select :sub_category_id, SubCategory.all.collect{ |cat| [cat.title, cat.id] } %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Products</h1>
<table>
   <tbody>
      <div class="container">
         <h3 class="h3">shopping Demo-1 </h3>
         <div class="row">
            <% @products.each do |product|%>
            <div class="col-md-3 col-sm-6">
               <div class="product-grid">
                  <div class="product-image">
                     <br>
                     <a href="#">
                     <%= image_tag product.image_url rescue nil%> 
                     </a>
                     <!-- <ul class="social">
                        <li><a href="" data-tip="Quick View"><i class="fa fa-search"></i></a></li>
                        </ul> -->
                     <!-- <span class="product-new-label">Sale</span>
                        <span class="product-discount-label">20%</span> -->
                  </div>
                  <!-- <ul class="rating">
                     <li class="fa fa-star"></li>
                     <li class="fa fa-star"></li>
                     <li class="fa fa-star"></li>
                     <li class="fa fa-star"></li>
                     <li class="fa fa-star disable"></li>
                     </ul> -->
                  <div class="product-content">
                     <h3 class="title"><a href="#"><%= product.title %></a></h3>
                     <!--  <div class="price">$16.00
                        <span>$20.00</span>
                        </div> -->
                     <% if Wishlist.where(user_id: current_user.id, product_id: product.id).present? %>
                     <%= link_to "/wishlists/#{Wishlist.where(user_id: current_user.id, product_id: product.id).last.id}/remove_to_wishlist" do %>
                     Remove To Wishlist
                     <% end %>
                     <% else %>
                     <%= link_to "/products/#{product.id}/add_to_wishlist" do %>
                     Add To Wishlist
                     <% end %>
                     <% end %>
                     ||
                     <%= link_to "/products/#{product.id}/add_to_cart" do %>
                     Add To Cart
                     <% end %>
                     ||
                     <li>

                        <% if current_user.present? %>
                        <% if Like.where(user_id: current_user, product_id: product.id).present? %>
                        <a href="/products/<%= product.id %>/dislike_products" data-tip="Dislike">DLike</a>
                        <% else%>
                        <a href="/products/<%= product.id %>/like_products" data-tip="Like">Like</a>
                        <% end %> 
                        <% end %> 
                     </li>
                  </div>
               </div>
               <br>
            </div>
            <% end %>
         </div>
      </div>
   </tbody>
</table>
<br>
<!-- <%# @products.each do |product| %>
   <tr>
   <td><%#= product.title %></td>
   <td><%#= product.description %></td>
   <td><%#= product.price %></td>
   <td>  <%#= image_tag product.image_url rescue nil%>
   </td>
   <td><%#= product.size %></td>
   <td><%#= product.sub_category_id %></td>
   <td><%#= link_to 'Show', product %></td>
   <td><%#= link_to 'Edit', edit_product_path(product) %></td>
   <td><%#= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
   <td>  <%#= link_to "/products/#{product.id}/add_to_cart" do %>
   Add To Cart
   
   
   <%# end %> </td>
   </tr>
   <%# end %> -->
<!--  </tbody>
   </table> -->

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/search.html.erb
<table>
 

  <tbody>
    <div class="container">
    <h3 class="h3">shopping Demo-1 </h3>
    <div class="row">
      <% @products.each do |product|%>
        <div class="col-md-3 col-sm-6">
            <div class="product-grid">
                <div class="product-image"><br>
                    <a href="#">
                        <%= image_tag product.image_url rescue nil%> 
                    </a>
                   
                    <!-- <ul class="social">
                        <li><a href="" data-tip="Quick View"><i class="fa fa-search"></i></a></li>
                    </ul> -->
                    <!-- <span class="product-new-label">Sale</span>
                    <span class="product-discount-label">20%</span> -->
                </div>


                <!-- <ul class="rating">
                    <li class="fa fa-star"></li>
                    <li class="fa fa-star"></li>
                    <li class="fa fa-star"></li>
                    <li class="fa fa-star"></li>
                    <li class="fa fa-star disable"></li>
                </ul> -->
                <div class="product-content">
                    <h3 class="title"><a href="#"><%= product.title %></a></h3>
                   <!--  <div class="price">$16.00
                        <span>$20.00</span>
                    </div> -->
    <% if Wishlist.where(user_id: current_user.id, product_id: product.id).present? %>
                        <%= link_to "/wishlists/#{Wishlist.where(user_id: current_user.id, product_id: product.id).last.id}/remove_to_wishlist" do %>
                          Remove To Wishlist
                    <% end %>
                    <% else %>
                     <%= link_to "/products/#{product.id}/add_to_wishlist" do %>
                          Add To Wishlist
                    <% end %>
                    <% end %>
                     ||
                    <%= link_to "/products/#{product.id}/add_to_cart" do %>
                          Add To Cart
                    <% end %>
                </div> 
            </div><br>
        </div> 
        <% end %>
      </div> 
    </div>
  </tbody>
</table>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @product.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Image:</strong>
  <%= image_tag @product.image_url rescue nil%>
</p>

<p>
  <strong>Size:</strong>
  <%= @product.size %>
</p>

<p>
  <strong>SubCategory:</strong>
  <%= @product.sub_category_id %>
</p>
<%= button_to 'Like', product_likes_path(@product), method: :post %>
<p><%= @product.likes.count %> <%= (@product.likes.count) == 1 ? 'Like' : 'Likes'%></p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>